<script src="<?php echo ADMIN_DIR_HTTP_JS ?>jquery-2.1.4.min.js"></script>
<script type="text/javascript">
    if ('ontouchstart' in document.documentElement) document.write("<script src='<?php echo ADMIN_DIR_HTTP_JS ?>jquery.mobile.custom.min.js'>" + "<" + "/script>");
</script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>bootstrap.min.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>jquery.bootstrap-duallistbox.min.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>jquery.raty.min.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>bootstrap-multiselect.min.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>select2.min.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>jquery-typeahead.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>jquery-ui.custom.min.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>jquery.ui.touch-punch.min.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>bootbox.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>jquery.easypiechart.min.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>jquery.gritter.min.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>spin.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>wizard.min.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>ace-elements.min.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>ace.min.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>dataTable.min.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>chosen.jquery.min.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>spinbox.min.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>bootstrap-datepicker.min.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>bootstrap-timepicker.min.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>moment.min.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>daterangepicker.min.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>bootstrap-datetimepicker.min.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>bootstrap-colorpicker.min.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>jquery.knob.min.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>autosize.min.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>jquery.inputlimiter.min.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>jquery.maskedinput.min.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>bootstrap-tag.min.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>bootstrap-wysiwyg.min.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>bootstrap-datepicker.min.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>bootstrap-timepicker.min.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>moment.min.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>daterangepicker.min.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>bootstrap-datetimepicker.min.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>bootstrap-colorpicker.min.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>jquery.cookie.min.js"></script>

<script src="<?php echo ADMIN_DIR_HTTP_JS ?>script.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>validation.js"></script>
<script src="<?php echo ADMIN_DIR_HTTP_JS ?>table.js"></script>
